language: python
python:
  - "3.4"
install:
  # pip compiles a lot of scipy and numpy C Code at installation. to enable fast
  # travis test we use an exotic package manager called miniconda, which provides
  # binary packages of numpy and scipy.
  #
  # This `.travis.yml` files is adapted from: http://conda.pydata.org/docs/travis.html
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  - echo "`sed 's/==/=/' < requirements.txt`"
  - CONDA_DEPS=$(grep -E 'numpy|scipy' requirements.txt | sed 's/==/=/')
  - PIP_DEPS=$(grep -vE 'numpy|scipy' requirements.txt )
  # Usefull for debugging
  - echo $CONDA_DEPS
  - echo $PIP_DEPS
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS pip
  - source activate test-environment
  - pip install $PIP_DEPS
  - python setup.py install
script:
  - ./travis.sh
after_success:
    coveralls
notifications:
  email: false
