before_install:
  # install numpy and scipy before, otherwise travis will compile them
  # everytime it runs the tests
  - sudo apt-get install -qq python-numpy python-scipy
virtualenv:
  system_site_packages: true
language: python
python:
  - "2.7"
install:
  # filter numpy and scipy
  - "grep -vE 'numpy|scipy' requirements.txt > .travis-requirements.txt"
  - "pip install -r .travis-requirements.txt"
script:
  - ./travis.sh
notifications:
  email: false
